version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: smt_arts_gallery_mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    container_name: smt_arts_gallery_backend
    restart: always
    environment:
      NODE_ENV: production
      PORT: 5000
      MONGODB_URI: mongodb://mongodb:27017/arts_gallery_db
    ports:
      - "5000:5000"
    depends_on:
      - mongodb

  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
    container_name: smt_arts_gallery_frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mongodb_data:
